---
title: "P8105 Homework 2"
author: "Jasmine Niu (jn2855)"
output: github_document
---

```{r}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```


```{r}
library(tidyverse)
library(readxl)
```


## Problem 1

```{r}
trans_ent = 
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

```{r}
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

```{r}
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

```{r}
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

```{r}
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct

trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```


## Problem 2

```{r}
mr_trash_df = read_excel(
  "data/Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N549"
    ) %>% 
  janitor::clean_names()
```

```{r}
pr_trash_df = read_excel(
  "data/Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M96"
    ) %>% 
  janitor::clean_names()
```


